In [15]:
import numpy as np

In [2]:
m=4
n=3
puddles= [[2,2]]

In [17]:
result = [[0]*(m+1) for i in range(n+1)]

In [18]:
np.array(result)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
result[1][1] = 1

In [27]:
np.array(result)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
for i in range(1,m+1):
    for j in range(1,n+1):
        if i==1 and j == 1:
            continue
        if [j,i] in puddles:
            result[j][i] = 0
        else:
            result[j][i] = result[j-1][i] + result[j][i-1]

In [31]:
np.array(result)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 1, 2],
       [0, 1, 1, 2, 4]])

In [33]:
result[n][m]

4

In [ ]:
def solution(m, n, puddles):
    answers=[[0]*(m+1) for i in range(n+1)]
    answers[1][1]=1
    for i in range(1,n+1):
        for j in range(1,m+1):
            if i==1 and j==1:
                continue
            if [j,i] in puddles:
                answers[i][j]=0
            else:
                answers[i][j]=answers[i-1][j]+answers[i][j-1]
    return answers[n][m]%1000000007